pub mod compress;

#[allow(unused_imports)]
pub use compress::*;

/// The minimal size at which to encode filesystem files.
pub const MIN_ENCODING_SIZE: u64 = 1024;

/// The maximal size at which to encode filesystem files.
pub const MAX_ENCODING_SIZE: u64 = 100 * 1024 * 1024;

/// The minimal size gain at which to preserve encoded filesystem files.
pub const MIN_ENCODING_GAIN: f64 = 1.1;

// Generated by build.rs - extension blacklist
include!(concat!(env!("OUT_DIR"), "/extensions.rs"));
